apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model-server
  template:
    metadata:
      labels:
        app: model-server
    spec:
      containers:
      - name: contenedor-model-server
        image: mariacastellanos/model-server:default
        env:
          - name: MODEL_PATH
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: MODEL_PATH
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /model
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /model
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
          - name: volume-train
            mountPath: /model
      volumes:
        - name: volume-train
          hostPath:
            path: /tmp
            type: DirectoryOrCreate

