FROM python:3.8.0
WORKDIR /app
COPY requirements-server-extra.txt .
RUN pip install -r requirements-server-extra.txt
COPY main-server-extra.py .
CMD ["flask","--app","main-server-extra.py","run","--host=0.0.0.0"]
